### PR TITLE
New file structure

### PR DESCRIPTION
**Pull request by AndCotOli**
New file structure for the project.

Includes:

- Export ggez
- `create_circle`, `create_rect` and `create_square` functions
- `random_bright_color` and `random_dark_color` functions
- Updated examples

# Warning: breaking changes
Old code **won't** work with this version
Look at the examples to get more information

### CODE REVIEW

**Comment by AndCotOli** [comment]
Issue #17

**Comment by AndCotOli** [comment]
## Added: 
```rust
run(game: &mut EventHandler, title: &str, author: &str)
// Accesible in bbggez::run::run
```
> As seen in PR #18 

```rust
run_dim(game: &mut EventHandler, width: f32, height: f32, title: &str, author: &str)
// Accesible in bbggez::run::run_dim
```

```rust
random_location(width: f32, height: f32) -> (f32, f32)
// Accesible in bbggez::utils::random_location
```
> As seen in PR #25 

## Updated:
Now `random_bright_color` and `random_dark_color` use Hsl to create the colors.
> As seen in PR #19 

## Fixed:
`creates_random_bright_color` test. 
> As seen in PR #19

**Comment by AndCotOli** [comment]
## Added
```rust
create_triangle(points: &[Point2<f32>; 3], color: Color, ctx: &mut Context)
```
```rust
create_equilateral_triangle(x: f32, y: f32, side: f32, color: Color, ctx: &mut Context)
```
> As seen in PR #31 

#### Random location example
> As seen in PR #32 

## Refactored
Now the tests are in the same file as the functions

**Comment by AndCotOli** [comment]
## Added
```rust
Timer
// Accesible by bbggez::timer::Timer
```
> As seen in #35 

## Fixed
`random_location` now returns `nalgebra::Vector2<f32>`.

## Refactored
Now all the examples use built-in functions from bbggez.

**Comment by BrooksPatton** [comment]
The structure is looking good. I'm wondering what everyone thinks about moving the tests into document tests like what we have for the random location? That way the tests are in the same file and we also create documentation for the website as well.

**Comment by BrooksPatton** [comment]
This is looking good, and I'm greenlighting it to be merged in as soon as the merge conflicts are resolved.

I hesitate to update your pull request with the fixes, do you want me to update them or do you want to fix them before I merge in the code @AndCotOli ?

**Comment by AndCotOli** [comment]
Everything is ready to go now @BrooksPatton

**Comment by BrooksPatton** [comment]
And we got it in!

**Pull request merged**
